/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaCliente_2_AlterarExcluirController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import util.Mascaras;

/**
 *
 * @author Rafael
 */
public class TelaCliente_2_AlterarExcluir extends javax.swing.JFrame {

    private final TelaCliente_2_AlterarExcluirController controller;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaCliente_2_AlterarExcluir() {
        initComponents();
        controller = new TelaCliente_2_AlterarExcluirController(this);
        
        //INICIALIZANDO MÁSCARAS DOS CAMPOS
        Mascaras.formataCPF(jFormattedTextFieldCPF);
        Mascaras.formataCEP(jFormattedTextFieldCEP);
        Mascaras.formataData(jFormattedTextFieldDataNascimento);
        Mascaras.formataTelefoneCelular(jFormattedTextFieldContatoCelular);
        Mascaras.formataTelefone(jFormattedTextFieldContatoTelefone);
        
        //INICIALIZAÇÃO DA TABELA
        controller.tabelaClientes();
        
        //INCIALIZAÇÃO DOS RÁDIO BUTTONS
        jRadioButtons();
                
    }
    
    public void jRadioButtons (){
        
        buttonGroup.add(jRadioButtonSim);
        buttonGroup.add(jRadioButtonNão);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelMensagem = new javax.swing.JLabel();
        jRadioButtonNão = new javax.swing.JRadioButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jLabelCEP = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelContatoCelular = new javax.swing.JLabel();
        jFormattedTextFieldContatoCelular = new javax.swing.JFormattedTextField();
        jLabelContato2 = new javax.swing.JLabel();
        jFormattedTextFieldContatoTelefone = new javax.swing.JFormattedTextField();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();
        jLabelBairroPesquisa = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelPainel = new javax.swing.JLabel();
        jLabelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeCompleto.setText("Nome Completo");
        getContentPane().add(jLabelNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        getContentPane().add(jTextFieldNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 420, 40));

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jFormattedTextFieldCPF.setToolTipText("Formato: xxx.xxx.xxx-xx");
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 130, 40));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 340, 40));

        jLabelDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNascimento.setText("Data Nascimento");
        getContentPane().add(jLabelDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jFormattedTextFieldDataNascimento.setToolTipText("Formato: dd/mm/yyyy");
        getContentPane().add(jFormattedTextFieldDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 130, 40));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Deseja receber emails?");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 220, 40));

        jLabelMensagem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagem.setText("Sexo");
        getContentPane().add(jLabelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jRadioButtonNão.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonNão.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNão.setText("Não");
        getContentPane().add(jRadioButtonNão, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        jRadioButtonSim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonSim.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSim.setText("Sim");
        jRadioButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSimActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, -1, -1));

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCEP.setText("CEP");
        getContentPane().add(jLabelCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jFormattedTextFieldCEP.setToolTipText("Formato: xx.xxx-xxx");
        jFormattedTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEPActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 40));

        jLabelRua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRua.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRua.setText("Rua");
        getContentPane().add(jLabelRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        getContentPane().add(jTextFieldRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 420, 40));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Número");
        getContentPane().add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 100, 40));

        jLabelComplemento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelComplemento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComplemento.setText("Complemento");
        getContentPane().add(jLabelComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, -1, -1));
        getContentPane().add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 100, 40));

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Bairro");
        getContentPane().add(jLabelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 40));

        jLabelContatoCelular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContatoCelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContatoCelular.setText("Contato 1 (Celular)");
        getContentPane().add(jLabelContatoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jFormattedTextFieldContatoCelular.setToolTipText("Formato: (xx)xxxxx-xxxx");
        jFormattedTextFieldContatoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldContatoCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldContatoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 130, 40));

        jLabelContato2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContato2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContato2.setText("Contato 2 (Telefone)");
        getContentPane().add(jLabelContato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        jFormattedTextFieldContatoTelefone.setToolTipText("Formato: (xx)xxxxx-xxxx");
        jFormattedTextFieldContatoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldContatoTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldContatoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 130, 40));

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome" }));
        jComboBoxPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 30));

        jLabelBairroPesquisa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBairroPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairroPesquisa.setText("Pesquisar por");
        getContentPane().add(jLabelBairroPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 570, 30));

        jButtonPesquisar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 330, 30));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codcliente", "Nome", "Cpf", "Email", "Data_nascimento", "Sexo", "Cep", "Rua", "Numero", "Complemento", "Bairro", "Contato1", "Contato2", "Recebe_email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPaneClientes.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(2).setResizable(false);
            jTableClientes.getColumnModel().getColumn(3).setResizable(false);
            jTableClientes.getColumnModel().getColumn(4).setResizable(false);
            jTableClientes.getColumnModel().getColumn(5).setResizable(false);
            jTableClientes.getColumnModel().getColumn(6).setResizable(false);
            jTableClientes.getColumnModel().getColumn(7).setResizable(false);
            jTableClientes.getColumnModel().getColumn(8).setResizable(false);
            jTableClientes.getColumnModel().getColumn(9).setResizable(false);
            jTableClientes.getColumnModel().getColumn(10).setResizable(false);
            jTableClientes.getColumnModel().getColumn(11).setResizable(false);
            jTableClientes.getColumnModel().getColumn(12).setResizable(false);
            jTableClientes.getColumnModel().getColumn(13).setResizable(false);
        }

        getContentPane().add(jScrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 1170, 250));

        jButtonSalvar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 330, 40));

        jButtonExcluir.setBackground(new java.awt.Color(255, 204, 204));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 330, 40));

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 330, 40));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 610));

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jRadioButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSimActionPerformed

        
    }//GEN-LAST:event_jRadioButtonSimActionPerformed

    private void jFormattedTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEPActionPerformed

    private void jFormattedTextFieldContatoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldContatoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldContatoCelularActionPerformed

    private void jFormattedTextFieldContatoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldContatoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldContatoTelefoneActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        
        controller.botaoVoltar();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        
        controller.mouseClicked();
        
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jComboBoxPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPesquisaActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        controller.botaoPesquisar();

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        controller.botaoSalvar();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        controller.botaoExcluir();
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente_2_AlterarExcluir().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBoxSexo() {
        return jComboBoxSexo;
    }

    public void setjComboBoxSexo(JComboBox<String> jComboBoxSexo) {
        this.jComboBoxSexo = jComboBoxSexo;
    }

    public JFormattedTextField getjFormattedTextFieldCEP() {
        return jFormattedTextFieldCEP;
    }

    public void setjFormattedTextFieldCEP(JFormattedTextField jFormattedTextFieldCEP) {
        this.jFormattedTextFieldCEP = jFormattedTextFieldCEP;
    }

    public JFormattedTextField getjFormattedTextFieldCPF() {
        return jFormattedTextFieldCPF;
    }

    public void setjFormattedTextFieldCPF(JFormattedTextField jFormattedTextFieldCPF) {
        this.jFormattedTextFieldCPF = jFormattedTextFieldCPF;
    }

    public JFormattedTextField getjFormattedTextFieldContatoCelular() {
        return jFormattedTextFieldContatoCelular;
    }

    public void setjFormattedTextFieldContatoCelular(JFormattedTextField jFormattedTextFieldContatoCelular) {
        this.jFormattedTextFieldContatoCelular = jFormattedTextFieldContatoCelular;
    }

    public JFormattedTextField getjFormattedTextFieldContatoTelefone() {
        return jFormattedTextFieldContatoTelefone;
    }

    public void setjFormattedTextFieldContatoTelefone(JFormattedTextField jFormattedTextFieldContatoTelefone) {
        this.jFormattedTextFieldContatoTelefone = jFormattedTextFieldContatoTelefone;
    }

    public JFormattedTextField getjFormattedTextFieldDataNascimento() {
        return jFormattedTextFieldDataNascimento;
    }

    public void setjFormattedTextFieldDataNascimento(JFormattedTextField jFormattedTextFieldDataNascimento) {
        this.jFormattedTextFieldDataNascimento = jFormattedTextFieldDataNascimento;
    }

    public JRadioButton getjRadioButtonNão() {
        return jRadioButtonNão;
    }

    public void setjRadioButtonNão(JRadioButton jRadioButtonNão) {
        this.jRadioButtonNão = jRadioButtonNão;
    }

    public JRadioButton getjRadioButtonSim() {
        return jRadioButtonSim;
    }

    public void setjRadioButtonSim(JRadioButton jRadioButtonSim) {
        this.jRadioButtonSim = jRadioButtonSim;
    }

    public JTable getjTableClientes() {
        return jTableClientes;
    }

    public void setjTableClientes(JTable jTableClientes) {
        this.jTableClientes = jTableClientes;
    }

    public JTextField getjTextFieldBairro() {
        return jTextFieldBairro;
    }

    public void setjTextFieldBairro(JTextField jTextFieldBairro) {
        this.jTextFieldBairro = jTextFieldBairro;
    }

    public JTextField getjTextFieldComplemento() {
        return jTextFieldComplemento;
    }

    public void setjTextFieldComplemento(JTextField jTextFieldComplemento) {
        this.jTextFieldComplemento = jTextFieldComplemento;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldNomeCompleto() {
        return jTextFieldNomeCompleto;
    }

    public void setjTextFieldNomeCompleto(JTextField jTextFieldNomeCompleto) {
        this.jTextFieldNomeCompleto = jTextFieldNomeCompleto;
    }

    public JTextField getjTextFieldNumero() {
        return jTextFieldNumero;
    }

    public void setjTextFieldNumero(JTextField jTextFieldNumero) {
        this.jTextFieldNumero = jTextFieldNumero;
    }

    public JTextField getjTextFieldRua() {
        return jTextFieldRua;
    }

    public void setjTextFieldRua(JTextField jTextFieldRua) {
        this.jTextFieldRua = jTextFieldRua;
    }

    public JComboBox<Object> getjComboBoxPesquisa() {
        return jComboBoxPesquisa;
    }

    public void setjComboBoxPesquisa(JComboBox<Object> jComboBoxPesquisa) {
        this.jComboBoxPesquisa = jComboBoxPesquisa;
    }

    public JTextField getjTextFieldPesquisa() {
        return jTextFieldPesquisa;
    }

    public void setjTextFieldPesquisa(JTextField jTextFieldPesquisa) {
        this.jTextFieldPesquisa = jTextFieldPesquisa;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<Object> jComboBoxPesquisa;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldContatoCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldContatoTelefone;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBairroPesquisa;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelContato2;
    private javax.swing.JLabel jLabelContatoCelular;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JRadioButton jRadioButtonNão;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
