/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaBarbeiro_2_AlterarExcluirController;

/**
 *
 * @author Rafael
 */
public final class TelaBarbeiro_2_AlterarExcluir extends javax.swing.JFrame {

    private final TelaBarbeiro_2_AlterarExcluirController controller;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaBarbeiro_2_AlterarExcluir() {
        initComponents();
        controller = new TelaBarbeiro_2_AlterarExcluirController(this);
        
        jRadioButtons();
                
    }
    
    public void jRadioButtons (){
        
        buttonGroup.add(jRadioButtonSim);
        buttonGroup.add(jRadioButtonNão);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelMensagem = new javax.swing.JLabel();
        jRadioButtonNão = new javax.swing.JRadioButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jLabelCEP = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldNumeroBairro = new javax.swing.JTextField();
        jLabelContato1 = new javax.swing.JLabel();
        jFormattedTextFieldContato1 = new javax.swing.JFormattedTextField();
        jLabelContato2 = new javax.swing.JLabel();
        jFormattedTextFieldContato2 = new javax.swing.JFormattedTextField();
        jScrollPaneBarbeiros = new javax.swing.JScrollPane();
        jTableBarbeiros = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelPainel = new javax.swing.JLabel();
        jLabelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeCompleto.setText("Nome Completo");
        getContentPane().add(jLabelNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        getContentPane().add(jTextFieldNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 420, 40));

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jFormattedTextFieldCPF.setToolTipText("Formato: xxx.xxx.xxx-xx");
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 130, 40));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 340, 40));

        jLabelDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNascimento.setText("Data Nascimento");
        getContentPane().add(jLabelDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jFormattedTextFieldDataNascimento.setToolTipText("Formato: dd/mm/yyyy");
        getContentPane().add(jFormattedTextFieldDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 130, 40));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Deseja receber emails?");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 220, 40));

        jLabelMensagem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagem.setText("Sexo");
        getContentPane().add(jLabelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jRadioButtonNão.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonNão.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNão.setText("Não");
        getContentPane().add(jRadioButtonNão, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        jRadioButtonSim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonSim.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSim.setText("Sim");
        jRadioButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSimActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, -1, -1));

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCEP.setText("CEP");
        getContentPane().add(jLabelCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jFormattedTextFieldCEP.setToolTipText("Formato: xx.xxx-xxx");
        jFormattedTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEPActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 40));

        jLabelRua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRua.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRua.setText("Rua");
        getContentPane().add(jLabelRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        getContentPane().add(jTextFieldRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 420, 40));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Número");
        getContentPane().add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 100, 40));

        jLabelComplemento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelComplemento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComplemento.setText("Complemento");
        getContentPane().add(jLabelComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, -1, -1));
        getContentPane().add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, 100, 40));

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Bairro");
        getContentPane().add(jLabelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(jTextFieldNumeroBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 40));

        jLabelContato1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContato1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContato1.setText("Contato 1");
        getContentPane().add(jLabelContato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jFormattedTextFieldContato1.setToolTipText("Formato: (xx)xxxxx-xxxx");
        jFormattedTextFieldContato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldContato1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldContato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 130, 40));

        jLabelContato2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContato2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContato2.setText("Contato 2");
        getContentPane().add(jLabelContato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        jFormattedTextFieldContato2.setToolTipText("Formato: (xx)xxxxx-xxxx");
        jFormattedTextFieldContato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldContato2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldContato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 130, 40));

        jTableBarbeiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Email", "Data Nascimento", "Sexo", "Recebe Emails"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneBarbeiros.setViewportView(jTableBarbeiros);
        if (jTableBarbeiros.getColumnModel().getColumnCount() > 0) {
            jTableBarbeiros.getColumnModel().getColumn(0).setResizable(false);
            jTableBarbeiros.getColumnModel().getColumn(1).setResizable(false);
            jTableBarbeiros.getColumnModel().getColumn(2).setResizable(false);
            jTableBarbeiros.getColumnModel().getColumn(3).setResizable(false);
            jTableBarbeiros.getColumnModel().getColumn(4).setResizable(false);
            jTableBarbeiros.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPaneBarbeiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 1170, 300));

        jButtonSalvar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSalvar.setText("Salvar");
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 330, 40));

        jButtonExcluir.setBackground(new java.awt.Color(255, 204, 204));
        jButtonExcluir.setText("Excluir");
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 330, 40));

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 330, 40));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 610));

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
                                                                                         
    
    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jRadioButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSimActionPerformed

        
    }//GEN-LAST:event_jRadioButtonSimActionPerformed

    private void jFormattedTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEPActionPerformed

    private void jFormattedTextFieldContato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldContato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldContato1ActionPerformed

    private void jFormattedTextFieldContato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldContato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldContato2ActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        
        controller.botaoVoltar();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBarbeiro_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBarbeiro_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBarbeiro_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBarbeiro_2_AlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBarbeiro_2_AlterarExcluir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldContato1;
    private javax.swing.JFormattedTextField jFormattedTextFieldContato2;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelContato1;
    private javax.swing.JLabel jLabelContato2;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JRadioButton jRadioButtonNão;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JScrollPane jScrollPaneBarbeiros;
    private javax.swing.JTable jTableBarbeiros;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldNumeroBairro;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
