/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaAgendarController;

/**
 *
 * @author Rafael
 */
public class TelaAgendar extends javax.swing.JFrame {

    private final TelaAgendarController controller;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaAgendar() {
        initComponents();
        controller = new TelaAgendarController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneAgendamentos = new javax.swing.JScrollPane();
        jTableAgendamentos = new javax.swing.JTable();
        jLabelCliente = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelBarbeiro = new javax.swing.JLabel();
        jComboBoxBarbeiro = new javax.swing.JComboBox<>();
        jLabelServico = new javax.swing.JLabel();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelValorData = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabelValorHora = new javax.swing.JLabel();
        jFormattedTextFieldHora = new javax.swing.JFormattedTextField();
        jLabelObservacao = new javax.swing.JLabel();
        jScrollPaneObservacao = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jButtonAgendar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelPainel = new javax.swing.JLabel();
        jLabelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Barbeiro", "Servico", "Valor", "Data", "Hora", "Observacao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneAgendamentos.setViewportView(jTableAgendamentos);
        if (jTableAgendamentos.getColumnModel().getColumnCount() > 0) {
            jTableAgendamentos.getColumnModel().getColumn(0).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(1).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(2).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(3).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(4).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(5).setResizable(false);
            jTableAgendamentos.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPaneAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 337, 1150, 270));

        jLabelCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEXTO" }));
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 400, 40));

        jLabelBarbeiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBarbeiro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBarbeiro.setText("Barbeiro");
        getContentPane().add(jLabelBarbeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jComboBoxBarbeiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEXTO" }));
        jComboBoxBarbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBarbeiroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBarbeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 400, 40));

        jLabelServico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Serviço");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEXTO" }));
        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 400, 40));

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 400, 40));

        jLabelValorData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelValorData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorData.setText("Data");
        getContentPane().add(jLabelValorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        getContentPane().add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 400, 40));

        jLabelValorHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelValorHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorHora.setText("Hora");
        getContentPane().add(jLabelValorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        getContentPane().add(jFormattedTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 400, 40));

        jLabelObservacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Observação");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jScrollPaneObservacao.setViewportView(jTextAreaObservacao);

        getContentPane().add(jScrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 650, 200));

        jButtonAgendar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAgendar.setText("Agendar");
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 320, 40));

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 320, 40));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 610));

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    private void jComboBoxBarbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBarbeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBarbeiroActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        
        controller.botaoVoltar();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<Object> jComboBoxBarbeiro;
    private javax.swing.JComboBox<Object> jComboBoxCliente;
    private javax.swing.JComboBox<Object> jComboBoxServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora;
    private javax.swing.JLabel jLabelBarbeiro;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelValorData;
    private javax.swing.JLabel jLabelValorHora;
    private javax.swing.JScrollPane jScrollPaneAgendamentos;
    private javax.swing.JScrollPane jScrollPaneObservacao;
    private javax.swing.JTable jTableAgendamentos;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
