/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Rafael
 */
public class TelaCliente_1_Opcoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaCliente_1_Opcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensagem = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterarExcluir = new javax.swing.JButton();
        jLabelPainel = new javax.swing.JLabel();
        jLabelImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemBarbeiro = new javax.swing.JMenuItem();
        jMenuItemServico = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuItemAgendar = new javax.swing.JMenuItem();
        jMenuItemAgendamentos = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMensagem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensagem.setText("O que você deseja fazer?");
        getContentPane().add(jLabelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jButtonCadastrar.setText("Alterar ou Excluir Cliente");
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 400, 40));

        jButtonAlterarExcluir.setText("Cadastrar Novo Cliente");
        getContentPane().add(jButtonAlterarExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 400, 40));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 610));

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 630));

        jMenuCadastro.setText("Cadastro");

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cliente-icon.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemBarbeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cliente-icon.png"))); // NOI18N
        jMenuItemBarbeiro.setText("Barbeiro");
        jMenuCadastro.add(jMenuItemBarbeiro);

        jMenuItemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/tesoura-icon.png"))); // NOI18N
        jMenuItemServico.setText("Serviço");
        jMenuCadastro.add(jMenuItemServico);

        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/usuario-icon.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuario");
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");

        jMenuItemAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/agenda-icon.png"))); // NOI18N
        jMenuItemAgendar.setText("Agendar");
        jMenuOperacao.add(jMenuItemAgendar);

        jMenuItemAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/agenda-icon.png"))); // NOI18N
        jMenuItemAgendamentos.setText("Agendamentos");
        jMenuItemAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentosActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuItemAgendamentos);

        jMenuBar1.add(jMenuOperacao);

        jMenuRelatorio.setText("Relatório");
        jMenuBar1.add(jMenuRelatorio);

        jMenuSair.setText("Sair");
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgendamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_1_Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_1_Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_1_Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_1_Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente_1_Opcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarExcluir;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAgendamentos;
    private javax.swing.JMenuItem jMenuItemAgendar;
    private javax.swing.JMenuItem jMenuItemBarbeiro;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemServico;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
